name: Build image and deploy to ECS
on: 
    push:
        branches:
            - main
    workflow_dispatch:

env:
  NODE_IMAGE_NAME: joke-api-ecs
  REACT_IMAGE_NAME: react-app-ecs
 
jobs:
  build-image-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
      - uses: actions/checkout@v4

      - name: Add details to Image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}
          tags: |
            latest
            v1.0.${{ github.run_number }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./API-jokes
          file: ./API-jokes/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
